### ISSUE TITLE
таска 42

### ISSUE THREAD

**Issue by BDM30** [DiscoDancer/Study#8]
- [x] установить годный yacc
- [x] получить новый список файлов
- [ ] разобраться с calc.yrd
- [x] попробовать сбилдить под VS15

**Comment by BDM30** [comment]
### установить годный yacc
- понял, что нужна 13 vs и короткий путь установки. 
- [ ] скачать vs13
- [ ] попробовать сбилдить еще раз

**Comment by BDM30** [comment]
# Новый список файлов
Нашел старую программу все ок, она работает.
Теперь хочу вывести имя файла / путь, отсортированные по имени файла.
А потом отдельно можно только 2+ одинаковые файлы вывести.

**Comment by DiscoDancer** [comment]
я смог!
